// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"go-playground/service/wire-practice/handler"
	"go-playground/service/wire-practice/infra"
	"go-playground/service/wire-practice/repository"
	"go-playground/service/wire-practice/usercase"
)

// Injectors from wire.go:

func InitTodoHandler(r *gin.Engine) *handler.TodoHandler {
	mongoClient := infra.GetMongoClient()
	todoRepository := repository.NewTodoRepository(mongoClient)
	httpClient := infra.GetHttpClient()
	httpRepository := repository.NewHttpRepository(httpClient)
	todoUserCase := usercase.NewTodoUserCase(todoRepository, httpRepository)
	todoHandler := handler.NewTodoHandler(r, todoUserCase)
	return todoHandler
}
